# - name: "Install list of packages" 
#   apt: name={{item}} state=installed
#   with_items:
#           - atop
#           - sysstat
#           - gcc
#           - libssl-dev
#           - python-selinux
#           - python-pip
#           - python



# - name: pip install -U pip
#   pip:
#     name: pip
#     state: latest
#
 - name: Update ATP package manager repositories cache
   become: true
   apt: 
     update_cache: yes

 - name: Upgrade installed packages
   become: true
   apt: 
     upgrade: dist
    
 - name: Remove swapfile from /etc/fstab
   mount:
     name: "{{ item }}"
     fstype: swap
     state: absent
   with_items:
     - swap
     - none

 - name: Check Swap
   shell: swapon -s
   register: check_swap

 - name: Disable swap
   command: swapoff -a
   when: not check_swap.stderr

 - name: Add an apt signing key for Docker
   apt_key:
     url: https://download.docker.com/linux/ubuntu/gpg
     state: present

 - name: Add apt repository for stable version
   apt_repository:
     repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable
     state: present

 - name: Add an apt signing key for k8s
   apt_key:
     url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
     state: present

 - name: Add apt repository for stable version
   apt_repository:
     repo: deb [arch=amd64] http://apt.kubernetes.io/ kubernetes-xenial main
     state: present
