 - name: Install docker
   apt: 
     name: "{{ packages }}"
     state: present
     update_cache: yes
   vars:
     packages:
     - docker.io
   notify:
     - docker status



 - name: Install kubernetes tools
   apt:
     name: "{{ packages }}"
     state: present
     update_cache: yes
   vars:
     packages:
     - kubeadm
     - kubelet
     - kubectl
